---
title: "Background"
---

<style>
p {
  text-align: justify;
}

blockquote {
  text-align: justify;
  font-size: 10pt;
}
</style>

<br>

*Note: We plan to also provide daily updates during the holiday period 2021/22, but cannot exclude occasional delays. Also, nowcasts may be less reliable if reporting delay patterns differ from the rest of the year.*

<br>

### FAQ

For a summary of the project see also [this article](https://www.covid19.statistik.uni-muenchen.de/pdfs/codag-bericht-24.pdf){target="_blank"} in the *CODAG Report* series (in German).

<details><summary>What is the goal of this platform?</summary>
<blockquote>
The main goal of this project is to estimate the 7-day hospitalization incidence for Germany and its states reliably and to assess recent trends based on incomplete data. The frequently referred to most recent values of the raw hospitalization incidence underestimate the true number of hospitalizations (see also answers to the other questions). Nowcasting corrections of these numbers allow for a better assessment of the current epidemic situation.
<br>
At the same time we have a scientific interest to compare different nowcasting methods and to assess whether the combination of different nowcasts yields more reliable results.
</blockquote>
</details>

<details><summary>What is the 7-day hospitalization incidence?</summary>
<blockquote>
We follow the definition by Robert Koch Institute. Today's seven-day hospitalization incidence is the number of hospitalized cases of COVID-19 (in absolute numbers or per 100.000 population) whose *Meldedatum*, i.e. the date when the respective infection was electronically recorded at the local health authorities was in the 7 preceding days. It is thus *not* equivalent to the number of new hospitalizations during the last 7 days. Also, the 7-day hospitalization incidence does not take into account whether the reason of hospitalization was COVID-19 or not.
<br>
Further information on the 7-day hospitalization incidence (in German) are available on the [GitHub site of Robert Koch-Institute](https://github.com/robert-koch-institut/COVID-19-Hospitalisierungen_in_Deutschland){target="_blank"}.
<br>
In this context we note that some German states (Bundesländer) also publish their own hospitalization incidences which follow different definitions (e.g., temporal aggregation by date of hospitalization rather than *Meldedatum* of the infection; see [this news item by NDR](https://www.ndr.de/nachrichten/info/Nach-MPK-Beschluss-Verwirrung-um-Hospitalisierungsinzidenz,hospitalisierungsinzidenz100.html){target="_blank"})). We focus exclusively on the indicator provided by RKI.
</blockquote>
</details>

<details><summary>Why are the reported values for the most recent days unreliable and why is that a problem?</summary>
<blockquote>
The *Meldedatum* and the date when a hospitalization first appears the data set at Robert Koch Institut can be several days or even weeks apart. Several aspects play a role here. Firstly, an infected person may not be in a state which requires hospitalization on the *Meldedatum*, but reach such a state at a later point. In this case, the number of hospitalizations for the respective *Meldedatum* will be retrospectively increased by one. Secondly, there can be reporting delays between the actual date of hospitalization and the appearance of the hospitalization in the RKI data.
<br>
The daily values of the hospitalization incidence aggregated by *Meldedatum* are thus usually corrected upwards during the following days and weeks. Most additions occur within a few days, so that the values for the last few days are most strongly affected. Oftentimes they considerably underestimate the true number of hospitalizations (see e.g. [this news item](https://www.ndr.de/nachrichten/info/Hospitalisierungsrate-zeigt-nur-noch-die-Haelfte-der-Corona-Patienten,hospitalisierungsrate102.html){target="_blank"} by the public broadcaster NDR or [CODAG-Report Nr. 21](https://www.covid19.statistik.uni-muenchen.de/pdfs/codag-bericht-21.pdf){target="_blank"} by LMU Munich; both in German). In particular, preliminary data can create the impression of a decreasing hospitalization incidence even if it is actually on the rise.
</blockquote>
</details>

<details><summary>What does that mean for the thresholds which have been defined for the hospitalization incidence?</summary>
<blockquote>
The thresholds of 1.5 and 5 [suggested by RKI in September  (Fig 1)](https://www.rki.de/DE/Content/InfAZ/N/Neuartiges_Coronavirus/Downloads/control-covid-2021-09-22.pdf?__blob=publicationFile) explicitly refer to preliminary values as available on the respective date (see "time series of frozen values" below). They thus take into account the incompleteness of the data. The  [governmental decision from 18 November 2021 (Paragraph 9)](https://www.bundesregierung.de/resource/blob/974430/1982598/defbdff47daf5f177586a5d34e8677e8/2021-11-18-mpk-data.pdf?download=1) does not address this distinction explicitly, but according to [media coverage](https://www.ndr.de/nachrichten/info/Fragen-und-Antworten-zur-Hospitalisierungsinzidenz,hospitalisierungsinzidenz102.html) the thresholds of 3, 6 and 9 are equally applied to the preliminary values.
</blockquote>
</details>

<details><summary>Is there a distinction between hospitalizations with COVID-19 as the main reason and hospitalizations of infected persons due to other reasons?</summary>
<blockquote>
The hospitalization incidence as defined by RKI does not take into account the main reason of hospitalization ("with or because of COVID"). Our analyses build directly upon this indicator and concern purely the problem of delays and incomplete most recent data points. The difficulty that only part of the hospitalizations are due to illness from COVID thus remains. To our knowledge there are currently no reliable data on this question. Given the presumably lower average severity of infections with the omicron variant it is possible that the share of hospitalizations where COVID is not the reason of hospitalization increases. This can limit the comparability of incidence values across different phases of the pandemic and needs to be taken into account in their interpretation. However, it should be noted that hospitalizations with COVID as a secondary diagnosis nonetheless imply additional efforts for hospitals, e.g. in terms of isolation measures. 
</blockquote>
</details>

<details><summary>What does nowcasting mean and how should nowcasts be interpreted?</summary>
<blockquote>
Nowcasting is a statistical tool which, based on preliminary data, estimates which value a given quantity will take once measurements are complete. In our application we estimate how many hospitalizations will be reported in total for a given *Meldedatum*. To this end, information on the hospitalizations already reported up to the current date and data on past reporting delays are used.
<br>
The term nowcasting typically refers to events which have already occurred, but have not been measured or reported completely. For instance, nowcasting methods can be used to estimate how many cases of COVID-19 have been detected on a given day before these information have been aggregated into a central data set. This is not exactly the case for the hospitalization incidence as it is possible that hospitalizations linked to a given *Meldedatum* have not even occurred yet at the time of nowcasting. We nonetheless use the term *nowcasting* as it has become common for this type of analysis.
<br>
The nowcasts presented here should be interpreted as probability statements. An exact estimation of the true number of hospitalizations is not feasible and nowcasts can merely provide a range of probable values (see below).
</blockquote>
</details>

<details><summary>Why are several different nowcasts shown? What is an ensemble nowcast?</summary>
<blockquote>
Nowcasts are always based on a number of assumptions. Moeover, different models may include different additional data sources. Therefore, results based on different approaches often vary, and it is reasonable to compare different nowcasts to get an idea of the range of predictions. Moreover it can be helpful to combine several nowcasts into a so-called ensemble nowcast to achieve a more robust estimation. This approach has shown benefits for instance in [weather forecasting](https://www.science.org/doi/abs/10.1126/science.1115255){target="_blank"}, but also in [epidmimological applications](https://www.medrxiv.org/content/10.1101/2021.02.03.21250974v2){target="_blank"}.
</blockquote>
</details>

<details><summary>Why is it important to provide uncertainty intervals?</summary>
<blockquote>
No model is perfect and the exact number of hospitalizations for a given *Meldedatum* canot be predicted exactly. The nowcasts displayed here therefore explicitly quantify their own uncertainty, i.e. they state how reliable they consider their own estimation. This is done via intervals which are supposed to contain the true value with a given probability (50% or 95%).
</blockquote>
</details>

<details><summary>How reliable are the nowcasts?</summary>
<blockquote>
The evaluation of the different methods is an important goal of this project (see below). However, it is in the nature of things that assessing the quality of nowcasts is only feasible after a some time has passed. The visualization tool enables the user to return to past data versions and nowcasts issued in the past to get an idea of their reliability. E.g., nowcasts for the state of Saxony from 18 November 2021 were considerably below the ultimately observed values, which was likely due to the overstrain of the reporting system (see next question).
</blockquote>
</details>

<details><summary>What are possible difficulties and weaknesses? When are results to be interpreted with special care?</summary>
<blockquote>
The central assumption on which most nowcasts are built is that the delays between the *Meldedatum* and the apppearance of a hospitalization in the RKI data set will follow similar patterns in the future as they did in the past. If this is not the case, e.g., due to major changes in testing strategies or an overload of the health system, the quality of nowcasts may suffer. For instance, if average delays get loner, nowcasts may tend to underestimate the true values. It must be assumed that this is currently (December 2021) the case for certain fedeal states, or may be the case in weeks to come.
</blockquote>
</details>

<details><summary>How often are nowcasts updated?</summary>
<blockquote>
Nowcasts are updated daily at around 1pm. As long as a team have not updated their nowcast yet, their nowcast from the previous day (or the most recent nowcasts which is not older than seven days) is displayed. 
<br>
Occasionally there may be delays, e.g. if input data from RKI become available later than usually. In this case we try to update nowcasts in a timely manner, but some models require a certain time to compute. **Over hte holiday period 2021/22 we expect such delays to occur occasionally, and updates may be considerably late or missing on certain days.**
</blockquote>
</details>

<details><summary>Why are nowcasts for the current and previous day not shown by default?</summary>
<blockquote>
For the last two days a particularly large number of additional reports must be expected. Therefore, nowcasts for these days are less reliable than for days which are further in the past. For this reason we do not show nowcasts for the last two days by default and recomend to interpret them with special care.
</blockquote>
</details>

<details><summary>What does the "time series by appearance in RKI data" show?</summary>
<blockquote>
An alternative to nowcasting the hospitalization incidence by *Meldedatum* (i.e. the day when the respective infection was electronically recorded by the local health authority, see above) is to aggregate hospitalizations by the day when they first appeared in the RKI data set. These numbers do not change over the following days, meaning that trends are more straightforward to interpret. Owing to reporting delays, the resulting curve is typically shifted to the right compared to the seven-day hospitalization incidence by *Meldedatum*.
</blockquote>
</details>


<details><summary>What does the "time series of frozen values" show?</summary>
<blockquote>
Another alternative to nowcasting is to show the 7-day hospitalization incidence for each *Meldedatum* based on the data version from the respective date. This way, all shown values will be similarly incomplete and more comparable over time. A downside of this approach is that it only exploits part of the information already available.
</blockquote>
</details>

<details><summary>What is meant by "retrospective nowcasts"?</summary>
<blockquote>
The main goal of this project is to provide nowcasts in real time to allow for an improved assessment of the current situation. However, in order to systematically compare different modelling approaches, we also collect nowcast which have been created retrospectively and evaluate how they would have performed in the past. For a fair comparison it is crucial that models only use data which would already have been available at the respective time of nowcasting.
</blockquote>
</details>

<br>

### Contributing research groups

This platform is run by members of the [Chair of Statistics and Econometrics](https://statistik.econ.kit.edu/index.php){target="_blank"} at Karlsruhe Institute of Technology and the [Computational Statistics Group](https://www.h-its.org/de/forschung/cst/){target="_blank"} at Heidelberg Institute for Theoretical Studies. Several other independent groups from academia and media contribute nowcasts (see also metadata files in our [GitHub repository](https://github.com/KITmetricslab/hospitalization-nowcast-hub/tree/main/data-processed){target="_blank"}):

- [Institute of Mathematics, TU Ilmenau](https://www.tu-ilmenau.de/stochastik/){target="_blank"}
- [Statistical Consulting Unit (StaBLab), LMU München](https://corona.stat.uni-muenchen.de/){target="_blank"}
- [RIVM (Rijksinstituut voor Volksgezondheid en Milieu), Bilthoven, the Netherlands](https://www.rivm.nl/en){target="_blank"}
- [Department of Mathematics, Stockholm University](https://www.su.se/english/profiles/fegu7762-1.554768){target="_blank"}
- [Süddeutsche Zeitung](https://www.sueddeutsche.de/thema/Coronavirus){target="_blank"}
- [London School of Hygiene and Tropical Medicine / epiforecasts](https://epiforecasts.io/){target="_blank"}

Moreover we display the most current [adjusted hospitalization incidences](https://github.com/robert-koch-institut/COVID-19-Hospitalisierungen_in_Deutschland){target="_blank"} from Robert Koch Institute.

<br>

### Methods descriptions

<details><summary>*ILM-prop* (TU Ilmenau)</summary>
<blockquote>
These Nowcasts are based on the proportion of the 7-day incidence of COVID-19 cases that appear in the hospitalization incidence after one, two etc. weeks. This model then multiplies todays known 7-day incidence by these weekly proportions and predicts todays 7-day hospitalization incidence by summing these up. 
The uncertainty is based on a log-normal (within age-groups) or normal (sum over all age groups) distribution where the dispersion is estimated based on retrospective application of the model.
</blockquote>
</details>

<details><summary>*KIT-simple_nowcast* (Karlsruher Institut für Technologie)</summary>
<blockquote>
Nowcasting is based on a simple estimation of the distribution of delays between the Meldedatum and appearance in the RKI data set (based on the last 60 days). From these, multiplication factors are derived and used for an upward correction of incomplete observations. To assess the nowcast uncertainty, the same corrected values are generated for past time points (based on the information available at the respective time) and compared to the subsequently observed values. To this end we assume a negative binomial distribution, where the dispersion parameter is a function of the time difference between Meldedatum and date of nowcast. Estimation of the dispersion parameter ist done via a maximum likelihood approach.
<br>
This method is purposefully kept simple and has the role of a reference/baseline model in our comparative evaluation study (see below). The central assumption is that delay distributions are temporally stable. Weekday effects and recent developments in case numbers are not accounted for.
</blockquote>
</details>


<details><summary>*LMU_StaBLab-GAM_nowcast* (LMU München)</summary>
<blockquote>
Nowcasts are based on a generalized additive model and the sequential multinomial structure of the time delay. The model is a slightly adapted version of the method by [Schneble et al. (2020)](https://onlinelibrary.wiley.com/doi/full/10.1002/bimj.202000143){target="_blank"} for nowcasting of fatal infections.
</blockquote>
</details>

<details><summary>*RIVM-KEW* (RIVM (Rijksinstituut voor Volksgezondheid en Milieu), Bilthoven, Niederlande)</summary>
<blockquote>
This model is a simplified version of the model presented by van de Kassteele, Eilers and Wallinga ([Epidemiology, 2019](https://doi.org/10.1097/ede.0000000000001050){target="_blank"}). The reported counts by date and delay are described by a negative binomial distribution. The expected values are modelled by a two-dimensional P-spline surface and other covariates. This surface is extrapolated for all dates and delays outside the reporting triangle. The nowcast is obtained by summing all counts over the delays by date. Prediction intervals are obtained by Monte Carlo simulation from the predictive distribution. This simplified model is without the calender time x delay interaction, the unimodality and boundary constraints. Model fitting is done efficiently using the [mgcv](https://cran.r-project.org/web/packages/mgcv/index.html){target="_blank"} package in R.
</blockquote>
</details>

<details><summary>*RKI-weekly_report* (Robert Koch Institut)</summary>
<blockquote>
These nowcasts are taken from the [weekly reports of the Robert Koch Institute](https://www.rki.de/DE/Content/InfAZ/N/Neuartiges_Coronavirus/Situationsberichte/Gesamt.html){target="_blank"} (updated on Thursdays). These are based on a modified version of the [nowcasting method for 7-day case incidences](https://www.rki.de/DE/Content/InfAZ/N/Neuartiges_Coronavirus/Projekte_RKI/Nowcasting.html){target="_blank"}.
<br>
As the RKI nowcasts are currently only communiated via the weekly reports, we read out the numbers from the respective figures, which may lead to minor imprecisions.
</blockquote>
</details>

<details><summary>*SU-hier_bayes* (Stockholm University)</summary>
<blockquote>
Nowcasts are based on a modified version of the model from [Günther et al 2020](https://onlinelibrary.wiley.com/doi/full/10.1002/bimj.202000112).
</blockquote>
</details>

<details><summary>*SZ-hosp_nowcast* (Süddeutsche Zeitung)</summary>
<blockquote>
SZ estimates the nowcasting values for the hospitalization incidence based on differences between the daily published and retrospectively corrected values resulting from later reports. To this end the archived data sets of Robert-Koch-Institute (https://github.com/robert-koch-institut/COVID-19-Hospitalisierungen_in_Deutschland) from the last 60 days are analysed. For each of the 25 days before the last date in the data set we compute by how many percent the later corrected value differs from the originally reported value. Quantiles of the resulting multiplication factors are computed, and the currently reported hospitalization incidence is multiplied with these quantiles to estimate the total incidence. Finally, the results are smoothed over a three-day window to remove unrealistic fluctuations.
</blockquote>
</details>

<details><summary>*epiforecasts-independent* (London School of Hygiene and Tropical Medicine / epiforecasts)</summary>
<blockquote>
A semi-parametric nowcasting method for right censored hospitalisations by date of positive test. Hospitalisations are modelled using a random walk on the log scale. Reporting delays are then modelled parametrically using a lognormal distribution with the log mean and log standard deviation each modelled using a weekly random walk with a pooled standard deviation. Report date effects are modelling using a random effect for day of the week with public holidays assumed to be reported like Sundays. Age groups and locations are nowcast independently (thus the name of the model). The model is implemented using the [epinowcast R package](https://epiforecasts.io/epinowcast){target="_blank"}. The analysis code is available [here](https://github.com/epiforecasts/eval-germany-sp-nowcasting). Note: There is a second version of this model currently not displayed in which the different time series are modelled in a hierarchical manner ([Epiforecasts-hierarchical](https://github.com/KITmetricslab/hospitalization-nowcast-hub/tree/main/data-processed/Epiforecasts-hierarchical){target="_blank"}).
</blockquote>
</details>

<br>

<details><summary>*NowcastHub-MeanEnsemble* </summary>
<blockquote>
This ensemble is created by taking quantile-wise means of the available member models providing complete nowcasts (28 days through 0 days before the current date).
</blockquote>
</details>

<details><summary>*NowcastHub-MedianEnsemble* </summary>
<blockquote>
This ensemble is created by taking quantile-wise medians of the available member models providing complete nowcasts (28 days through 0 days before the current date).
</blockquote>
</details>

<br>

### GitHub Repository and re-use of results

All nowcasts are available under open licences in a [public GitHub repository](https://github.com/KITmetricslab/hospitalization-nowcast-hub). They can be re-used for a broad range of purposes provided that the source is acknowledged (check the respective license files in the repository for details). You are invited to briefly get in touch with the organizing team or the creators of the respective nowcasts when re-using them publicly.

<br>

### Evaluation study

We are planning to compare the different nowcasting methods in a prospective evaluation study. To this end we have deposited a [public study protocol](https://osf.io/mru75/){target="_blank"} (similar to the [protocol](https://osf.io/zkdvb/){target="_blank"} of a recent [study on short-term predictions](https://www.nature.com/articles/s41467-021-25207-0){target="_blank"}).

<br>

### Related projects and analyses

If you find this platform interesting you may also want to check out:

- The [European](https://covid19forecasthub.eu/){target="_blank"}, [US](https://covid19forecasthub.org/){target="_blank"} and [German/Polish](https://kitmetricslab.github.io/forecasthub/){target="_blank"} COVID-19 Forecast Hubs on short-term forecasts of cases and deaths (one through four weeks ahead).
- [Nowcasting of case numbers and the effective reproductive number in Germany](https://www.rki.de/DE/Content/InfAZ/N/Neuartiges_Coronavirus/Projekte_RKI/Nowcasting.html){target="_blank"} by Robert Koch Institute.
- [Nowcasting of case numbers and the effective reproductive number in Bavaria](https://corona.stat.uni-muenchen.de/nowcast/){target="_blank"} by the CODAG group at LMU Munich.
- The [US Scenario Modelling Hub](https://covid19scenariomodelinghub.org/){target="_blank"} on longer-term scenario projections.
