---
title: "Hintergrund"
---

<style>
p {
  text-align: justify;
}

blockquote {
  text-align: justify;
  font-size: 10pt;
}
</style>

<br>
*Hinweis: Nowcasts können weniger verlässlich sein, wenn sich Meldeverzögerungen z.B. aufgrund starken Meldeaufkommens anders verhalten als in früheren Phasen der Pandemie. Außerdem ist zu beachten, dass sich der Anteil der in der Hospitalisierungsinzidenz erfassten Personen, bei denen COVID-19 tatsächlich der primäre Hospitalisieurngsgrund ist über die Zeit ändern kann (z.B. aufgrund der vermutlich milderen Omikron-Variante). Dies schränkt de Vergleichbarkeit über verschiedene Zeiträume hinweg ein.*
<br>

### FAQ

Für eine Zusammenfassung des Projekts siehe auch [diesen Artikel](https://www.covid19.statistik.uni-muenchen.de/pdfs/codag-bericht-24.pdf){target="_blank"} in der *CODAG Report*-Reihe

<details><summary>Was ist das Ziel dieser Plattform?</summary>
<blockquote>
Das Hauptziel dieses Projekts besteht darin, die Werte der 7-Tages-Hospitalisierungsinzidenz für Deutschland und die Bundesländer zuverlässig zu schätzen und aus vorläufigen Daten aktuelle Trends herauszuarbeiten. Die häufig angegebenen jeweils neuesten Werte der rohen Hospitalisierungsinzidenz unterschätzen die entsprechende wahre Zahl der Hospitalisierungen (siehe dazu die Antworten zu den weiteren Fragen). Nowcast-Korrekturen dieser Zahlen erlauben eine bessere Einschätzung der derzeitigen epidemischen Lage.
<br>
Gleichzeitig haben wir ein wissenschaftliches Interesse, verschiedene Nowcasting-Verfahren miteinander zu vergleichen und zu untersuchen, ob die Kombination verschiedener Nowcasts zu verlässlicheren Ergebnissen führt.
</blockquote>
</details>

<details><summary>Was ist die 7-Tage-Hospitalisierungsinzidenz?</summary>
<blockquote>
Wir richten uns hier nach der Definition des Robert-Koch-Instituts. Die heutige 7-Tage-Hospitalisierungsinzidenz ist die Anzahl an hospitalisierten COVID-19 Fällen (absolut oder pro 100.000 Einwohner) deren Meldedatum, also das Datum an dem das lokale Gesundheitsamt die zugehörige COVID-19 Infektion elektronisch erfasst hat, in den 7 vorangegangenen Tagen liegt. Es handelt sich also *nicht* um die Zahl der neuen Hospitalisierungen in den letzten 7 Tagen. Auch berücksichtigt die 7-Tage-Hospitalisierungsinzidenz nicht, ob der Hospitalisierungsgrund COVID-19 oder ein anderer ist (siehe nächste Frage).
<br>
Weitere Informationen sowie die aktuellen und vergangenen 7-Tage-Hospitalisierungsinzidenzen finden sich auf der [GitHub Seite des Robert Koch-Instituts](https://github.com/robert-koch-institut/COVID-19-Hospitalisierungen_in_Deutschland){target="_blank"}.
<br>
Wir weisen in diesem Zusammenhang darauf hin, dass manche Bundesländer auch eigene Hospitalisiserungsinzidenzen veröffentlichen, deren Definitionen von der des RKI abweichen (z.B. zeitliche Aggregierung nach Hospitalisierungsdatum statt Meldedatum der Infektion; siehe [Nachrichtenartikel des NDR](https://www.ndr.de/nachrichten/info/Nach-MPK-Beschluss-Verwirrung-um-Hospitalisierungsinzidenz,hospitalisierungsinzidenz100.html){target="_blank"}). Wir betrachten ausschließlich den Indikator des RKI.
</blockquote>
</details>

<details><summary>Wird unterschieden zwischen Hospitalisierungen, bei denen COVID-19 der Hauptgrund der Hospitalisierung ist und solchen, bei denen dies nicht der Fall ist?</summary>
<blockquote>
Die Hospitalisierungsinzidenz wie vom RKI definiert unterscheidet nicht nach dem Hauptgrund der Hospitalisierung ("mit oder wegen COVID"). Unsere Analysen bauen auf diesem Indikator auf und betreffen einzig die Problematik der Verzüge und der resultierenden Unvollständigkeit der letzten Inzidenzwerte (siehe nächste Frage). Die Schwierigkeit, dass nur ein Teil der erfassten Hospitalisierungen tatsächlich aufgrund einer COVID-Erkrankung erfolgen verbleibt also. Nach unserem Kenntnisstand stehen derzeit auf Bundesebene keine belastbaren Daten zu dieser Frage zur Verfügung. Mit der mutmaßlich im Mittel milder verlaufenden Omikron-Variante ist es möglich, dass sich der Anteil an Hospitalisierungen, bei denen COVID nur eine Begleiterscheinung ist, erhöht. Dies kann die Vergleichbarkeit der Inzidenzwerte über die verschiedenen Phasen der Pandemie hinweg einschränken und muss bei der Interpretation berücksichtigt werden. Allerdings ist auch zu beachten, dass selbst eine Hospitalisierung, bei der COVID nicht der Einlieferungsgrund ist für die Krankenhäuser Zusatzaufwand bedeutet, etwa aufgrund von Isolationsmaßnahmen.
<br>
Eine umfassendere Darstellung dieser Thematik findet sich für die Bundesländer [Rheinland-Pfalz](https://www.swr.de/swraktuell/rheinland-pfalz/mit-oder-wegen-corona-im-krankenhaus-100.html){target="_blank"} und [Baden-Württemberg](https://www.swr.de/swraktuell/baden-wuerttemberg/was-sagt-die-hospitalisierungsinzidenz-in-der-omikron-welle-aus-100.html){target="_blank"} in Nachrichtenartikeln des SWR. Demzufolge entfiel Ende Januar 2022 in Rheinland-Pfalz nur etwa ein Drittel der Hospitalisierungsinzidenz auf Fälle mit COVID-19 als primärem Hospitalisierungsgrund, während es in Baden-Württemberg fast zwei Drittel waren. Analysen für die Länder Bayern und Saarland finden sich im [CODAG-Bericht Nr. 26](https://www.covid19.statistik.uni-muenchen.de/pdfs/codag-bericht-26.pdf){target="_blank"} der LMU München.
</blockquote>
</details>

<details><summary>Warum sind die berichteten Werte der letzten Tage unzuverlässig und warum ist das ein Problem?</summary>
<blockquote>
Zwischen dem Meldedatum und dem Datum, an welchem ein hospitalisierter Fall vom Robert Koch-Institut in die 7-Tage-Hospitalisierungsinzidenz aufgenommen wird, können mehrere Tage oder sogar Wochen vergehen. Hier spielen mehrere Faktoren eine Rolle. Erstens kann es sein, dass eine Person am Meldedatum nicht in einem Zustand ist, der eine Hospitalisierung erfordert, jedoch später hospitalisiert werden muss. In diesem Fall wird rückwirkend die Zahl der Hospitalisierungen für das entsprechende Meldedatum um eins erhöht. Zweitens kann es Meldeverzüge zwischen dem tatsächlichen Hospitalisierungsdatum und der Erfassung der Hospitalisierungen in den Daten des RKI geben.
<br>
Deswegen werden die täglichen nach Meldedatum ausgewiesenen Hospitalisierungen in der Regel nachträglich nach oben korrigiert. Die meisten Nachtragungen erfolgen innerhalb von wenigen Tagen, sodass vor allem die Werte der jeweils letzten Tage betroffen sind. Diese unterschätzen die tatsächlichen Hospitalisierungen oft deutlich (siehe z.B. [diesen Nachrichtenartikel](https://www.ndr.de/nachrichten/info/Hospitalisierungsrate-zeigt-nur-noch-die-Haelfte-der-Corona-Patienten,hospitalisierungsrate102.html){target="_blank"} des NDR oder [CODAG-Bericht Nr. 21](https://www.covid19.statistik.uni-muenchen.de/pdfs/codag-bericht-21.pdf){target="_blank"} der LMU München). Das macht es sehr schwierig, aktuelle Tendenzen aus der rohen 7-Tage-Hospitalisierungsinzidenz abzulesen. Insbesondere kann der Eindruck einer fallenden Hospitalisierungsinzidenz entstehen, selbst wenn diese in Wirklichkeit steigt.
</blockquote>
</details>

<details><summary>Was bedeutet das für die Schwellenwerte, die für die 7-Tage-Hospitalisierungsinzidenz festgelegt wurden?</summary>
<blockquote>
Die im September 2021 [vom RKI vorgeschlagenen Schwellenwerte  (Abbildung 1)](https://www.rki.de/DE/Content/InfAZ/N/Neuartiges_Coronavirus/Downloads/control-covid-2021-09-22.pdf?__blob=publicationFile) von 1.5 und 5 beziehen sich ausdrücklich auf die vorläufigen tagesaktuell berichteten Werte (siehe Punkt "eingefrorene Zeitreihe" unten). Sie beziehen die Unvollständigkeit der Daten also mit ein.
Der [Regierungsbeschluss vom 18.11.2021 (Punkt 9)](https://www.bundesregierung.de/resource/blob/974430/1982598/defbdff47daf5f177586a5d34e8677e8/2021-11-18-mpk-data.pdf?download=1) spezifiziert nicht explizit, ob sich die Schwellenwerte 3, 6 und 9 auf vorläufige tagesaktuelle oder auf finale Werte beziehen. [Medienberichten](https://www.ndr.de/nachrichten/info/Fragen-und-Antworten-zur-Hospitalisierungsinzidenz,hospitalisierungsinzidenz102.html) zufolge werden Schwellenwerte allerdings ebenfalls auf die vorläufigen tageaktuellen Werte angewendet.
</blockquote>
</details>

<details><summary>Was bedeutet Nowcasting und wie sollten die Nowcasts interpretiert werden?</summary>
<blockquote>
Nowcasting bezeichnet ein statistisches Korrekturverfahren, das ausgehend von vorläufigen Messungen schätzt, welchen Wert die selben Größen in einer späteren finalen Version eines Datensatzes annehmen werden. In unserem Anwendunsfall schätzen wir beruhend auf den Hospitalisierungen, die bis zum heutigen Tag für ein bestimmtes Meldedatum (siehe oben) bekannt geworden sind, wie hoch die Zahl der Hospitalisierungen für dieses Datum nach Vorliegen aller Meldungen insgesamt liegen wird. Dabei werden Daten aus der Vergangenheit mit vollständiger Information genutzt.  
<br>
Klassischerweise bezieht sich Nowcasting auf Ereignisse, die bereits eingetreten sind, aber noch nicht vollständig gemessen oder erfasst sind. Bei COVID-19-Fallzahlen schätzt man mittels Nowcasting-Verfahren beispielsweise, wie viele Infektionen insgesamt an einem bestimmten Tag erfasst worden sind bevor diese Daten vollständig an zentraler Stelle zusammengetragen sind. Im Fall der Hospitalisierungen trifft dies nicht ganz zu, denn es ist möglich, dass Hospitalisierungen, die einem bestimmten (Fall-)Meldedatum zuzuordnen sind zum Zeitpunkt des Nowcasts noch gar nicht passiert sind. Wir verwenden dennoch den Begriff des *Nowcasting*, der sich auch für diese Art von Analyse eingebürgert hat.
<br>
Die hier präsentierten Nowcasts sollten als Wahrscheinlichkeitsaussagen interpretiert werden. Eine exakte Bestimmung der tatsächlichen Hospitalisierungszahl ist nicht möglich und Nowcasts geben lediglich einen Bereich wahrscheinlicher Werte an (siehe unten).
</blockquote>
</details>

<details><summary>Wieso werden mehrere verschiedene Nowcasts gezeigt? Was ist ein Ensemble-Nowcast?</summary>
<blockquote>
Bei der Erstellung von Nowcasts wird stets eine Reihe von Annahmen getroffen. Zudem können unterschiedliche Modelle unterschiedliche zusätzliche Datenquellen mit einbeziehen. Daher können sich die Ergebnisse verschiedener Verfahren unterscheiden, und es ist es sinnvoll, mehrere Nowcasts zu vergleichen und die Bandbreite der Vorhersagen zu berücksichtigen. Zudem kann es vorteilhaft sein, verschiedene Nowcasts in einem sogenannten Ensemble-Nowcast zusammenzuführen, um eine robustere Schätzung zu erhalten. Dies hat sich beispielsweise in der [Wettervorhersage](https://www.science.org/doi/abs/10.1126/science.1115255){target="_blank"}, aber auch in [epidemiologischen Anwendungen](https://www.medrxiv.org/content/10.1101/2021.02.03.21250974v2){target="_blank"} bewährt.
<br>
Hinweis: Die im Ensemble zusammengefassten Modelle sind unter Umständen nicht jeden Tag die selben (z.B. werden am Wochenende manche Modelle aktualisiert, andere nicht). Dadurch kann es sein, dass das Ensemble an aufeinanderfolgenden Tagen etwas unterschiedlich aussieht.
</blockquote>
</details>

<details><summary>Warum ist es wichtig, Unsicherheitsintervalle mit anzugeben?</summary>
<blockquote>
Kein Modell ist perfekt und die genaue Zahl der Hospitalisierungen zu einem bestimmten Meldedatum kann nicht exakt vorhergesagt werden. Die Nowcasts, die hier dargestellt werden, quantifizieren deshalb explizit ihre Unsicherheit, d.h. geben mit an, als wie verlässlich sie ihre eigene Schätzung ansehen. Dies geschieht mittels Intervallen, die den wahren Wert mit einer bestimmten Wahrscheinlichkeit (50% oder 95%) enthalten sollen.
</blockquote>
</details>

<details><summary>Wie verlässlich sind die Nowcasts?</summary>
<blockquote>
Die Evaluation der verschiedenen Verfahren ist ein wichtiges Ziel dieses Projekts (siehe unten). Jedoch liegt es in der Natur des Problems, dass erst mit größerem zeitlichem Abstand systematisch ausgewertet werden kann, wie zuverlässig die Nowcasts waren. Das Visualisierungs-Tool erlaubt es, mittels der Datumsauswahl zu früheren Datenständen und den damals erstellten Nowcasts zurückzukehren und so einen Eindruck von der Qualität der Nowcasts zu gewinnen. Z.B. der Nowcast für Sachsen vom 18. November liegt deutlich unter den in der Folge beobachteten Werten, was vermutlich der Überlastung des Meldesystems geschuldet ist (siehe nächste Frage).
</blockquote>
</details>

<details><summary>Was sind mögliche Probleme und Schwächen? Wann muss man bei der Interpretation besonders vorsichtig sein?</summary>
<blockquote>
Die zentrale Annahme, auf der die meisten Nowcasts beruhen ist, dass die Verzögerungen zwischen Meldedatum und Erscheinen einer Hospitalisierung in den Daten des RKI auch in Zukunft ähnlichen Mustern folgen werden wie in der Vergangenheit. Ist dies nicht mehr der Fall, etwa aufgrund gewichtiger Änderungen der Teststrategie oder einer Überlastung der Gesundheitsämter, so kann die Qualität der Nowcasts beeinträchtigt werden. Werden etwa die mittleren Verzögerungen größer, so können die Nowcasts dazu neigen, die wahren Werte zu unterschätzen.
</blockquote>
</details>

<details><summary>Wie oft werden die Nowcasts aktualisiert?</summary>
<blockquote>
Die Nowcasts werden täglich gegen 13:00 aktualisiert. Solange ein Team seinen Nowcast noch nicht aktualisiert hat wird der Nowcast des Vortages angezeigt (oder der neueste Nowcast aus den letzten sieben Tagen).
<br>
Gelegentlich kann es zu Verzögerungen kommen, z.B. wenn die Ausgangsdaten des RKI später als gewöhnlich online erscheinen. Wir versuchen, auch in diesem Fall zeitnah aktualisierte Nowcasts zu erstellen, jedoch benötigen manche der Modelle eine gewisse Rechenzeit.
</blockquote>
</details>

<details><summary>Wieso gibt es eine Schaltfläche, um die Nowcasts des heutigen und gestrigen Tages auszublenden?</summary>
<blockquote>
Für den heutigen und gestrigen Tag werden besonders viele Fälle nachgemeldet. Dadurch sind auch die Nowcasts für diese Tage weniger zuverlässig als für Tage, die weiter in der Vergangenheit liegen. Zu Beginn unseres Projektes zeigten wir die Nowcasts für den heutigen und gestrigen Tag aus diesem Grund standardmäßig nicht an. Mittlerweile konnten wir feststellen, dass die Nowcasts für diese beiden Tage ähnlich zuverlässig wie für die anderen Tage funktionieren, wenn man die breiteren Unsicherheitsintervalle mit einbezieht. Wir haben deshalb entschieden, sie nun standardmäßig mit einzublenden.
</blockquote>
</details>

<details><summary>Was zeigt die "Zeitreihe nach Erscheinen in RKI-Daten"?</summary>
<blockquote>
Eine Alternative zum Nowcast der Hospitalisierungsinzidenz nach Meldedatum (also dem Datum, an dem die Infektion im lokale Gesundheitsamt elektronisch erfasst wurde, siehe oben) ist es, Hospitalisierungszahlen nach dem Zeitpunkt ihres Auftauchens im Datensatz des RKI zu aggregieren. Diese Zahlen ändern sich in den darauffolgenden Tagen nicht mehr, sodass Trends einfacher zu interpretieren sind. Die resultierende Kurve ist gegenüber der 7-Tages-Inzidenz nach Meldedatum in der Regel nach rechts verschoben, da es oft eine Verzögerung zwischen dem Meldedatum und dem Auftauchen einer Hospitalisierung in den Daten gibt.
</blockquote>
</details>

<details><summary>Was zeigt die "Zeitreihe eingefrorener Werte"?</summary>
<blockquote>
Eine weitere Alternative zum Nowcasting besteht darin, für jedes Meldedatum die 7-Tage-Hospitalisierungsinzidenz gemäß des Datenstandes am jeweiligen Datum zu zeigen. Hierdurch sind alle gezeigten Werte ähnlich unvollständig und somit besser über die Zeit hinweg vergleichbar. Ein Nachteil dieser Herangehensweise ist, dass nur ein Teil der bereits verfügbaren Information genutzt wird.
</blockquote>
</details>

<details><summary>Was ist mit "nachträglich erstellten Nowcasts" gemeint?</summary>
<blockquote>
Das Hauptziel dieses Projekts ist es, Nowcasts in Echtzeit zur Verfügung zu stellen um eine verbesserte Lageeinschätzung zu ermöglichen. Um verschiedene Modellierungsansätze besser wissenschaftlich vergleichen zu können, sammeln wir aber auch Nowcasts, die rückwirkend erzeugt wurden. So können wir evaluieren, wie diese in der Vergangenheit abgeschnitten hätten. Wichtig für einen fairen Vergleich ist hierbei, dass auch bei den nachträglich erstellten Nowcasts nur Daten in das Modell einfließen, die zum jeweiligen Nowcast-Zeitpunkt bereits verfügbar waren.
</blockquote>
</details>

<br>

### Beteiligte Gruppen

Diese Plattform wird von Mitgliedern des [Lehrstuhls für Ökonometrie und Statistik](https://statistik.econ.kit.edu/index.php){target="_blank"} am Karlsruher Institut für Technologie sowie der [Computational Statistics Gruppe](https://www.h-its.org/de/forschung/cst/){target="_blank"} am Heidelberger Institut für Theoretische Studien betrieben. Mehrere unabhängige weitere Gruppen aus Wissenschaft und Medien tragen Nowcasts bei (siehe auch Metadata-Files in unserem [GitHub Repository](https://github.com/KITmetricslab/hospitalization-nowcast-hub/tree/main/data-processed){target="_blank"}):

- [Institut für Mathematik, TU Ilmenau](https://www.tu-ilmenau.de/stochastik/){target="_blank"}
- [Statistisches Beratungslabor, LMU München](https://corona.stat.uni-muenchen.de/){target="_blank"}
- [RIVM (Rijksinstituut voor Volksgezondheid en Milieu), Bilthoven, Niederlande](https://www.rivm.nl/en){target="_blank"}
- [Department Mathematik, Universität Stockholm](https://www.su.se/english/profiles/fegu7762-1.554768){target="_blank"}
- [Süddeutsche Zeitung](https://www.sueddeutsche.de/thema/Coronavirus){target="_blank"}
- [London School of Hygiene and Tropical Medicine / epiforecasts](https://epiforecasts.io/){target="_blank"}


Außerdem zeigen wir die [adjustierten Hospitalisierungsinzidenzen](https://github.com/robert-koch-institut/COVID-19-Hospitalisierungen_in_Deutschland){target="_blank"} des Robert Koch Instituts.

<br>

### Methodenbeschreibungen

<details><summary>*ILM-prop* (TU Ilmenau)</summary>
<blockquote>
Diese Nowcasts verwenden die in der Vergangenheit beobachteten an der 7-Tage-Inzidenz der COVID-19 Fällen anteiligen 7-Tage-Hospitalisierungsinzidenz nach einer, zwei usw. Wochen. Von der heute bekannten 7-Tage-Inzidenz werden dann diese Anteile berechnet und aufsummiert um die finale Anzahl an 7-Tage-Hospitalisierungen vorherzusagen. Die Unsicherheit wird durch Anwendung der Methode auf vergangene Zeitpunkte quantifiziert, wobei eine Log-Normalverteilung (Altersgruppen) beziehungsweise Normalverteilung (Summe über alle Altersgruppen) für die Vorhersagefehler angesetzt wird.
<br>
Die Hauptannahme dieses Verfahrens ist, dass sich der Anteil von Hospitalisierungen an der 7-Tage-Inzidenz und die Verzüge von Meldedatum des Falls bis dieser in den RKI-Daten erscheint nur langsam ändert.
</blockquote>
</details>

<details><summary>*KIT-simple_nowcast* (Karlsruher Institut für Technologie)</summary>
<blockquote>
Das Nowcasting beruht auf einer einfachen Schätzung der Verteilung der Verzögerungsdauern zwischen Meldedatum und Erscheinen einer Hospitalisierung in den RKI-Daten (basierend auf den letzten 60 Tagen). Aus diesen werden Multiplikationsfaktoren abgeleitet, mit denen die jeweils unvollständigen aktuellsten Beobachtungen nach oben korrigiert werden. Um die Nowcast-Unsicherheit zu beurteilen werden derartige korrigierte Werte auch für vergangene Zeitpunkte (basierend jeweils auf der damals verfügbaren Information) generiert und mit den entsprechenden später gemachten Beobachtungen verglichen. Hierfür wird eine negative Binomialverteilung angenommen, deren Streuungsparameter vom zeitlichen Abstand zwischen Meldedatum und Zeitpunkt des Nowcats abhängt. Die Schätzung der Streuungsparameter erfolgt mittels der Maximum Likelihood-Methode.
<br>
Dieses Verfahren ist bewusst einfach gehalten und hat die Funktion eines Referenz-/Baseline-Modells in unserer vergleichenden Evaluationsstudie (siehe unten). Die zentrale Annahme besteht darin, dass die Struktur der Meldeverzüge zeitlich stabil bleibt. Z.B. Wochentagseffekte oder Entwicklungen der Fallzahlen werden nicht berücksichtigt.
</blockquote>
</details>


<details><summary>*LMU_StaBLab-GAM_nowcast* (LMU München)</summary>
<blockquote>
Die Nowcasts beruhen auf einem generalisierten additiven Modell und der sequenziellen Multinomialstruktur der zeitlichen Verzögerungen. Das Modell ist eine geringfügig angepasste Version des Verfahrens von [Schneble et al. (2020)](https://onlinelibrary.wiley.com/doi/full/10.1002/bimj.202000143){target="_blank"} zum Nowcasting von tödlich verlaufenden Infektionen.
</blockquote>
</details>


<details><summary>*RIVM-KEW* (RIVM (Rijksinstituut voor Volksgezondheid en Milieu), Bilthoven, Niederlande)</summary>
<blockquote>
Dieses Modell ist eine vereinfachte Version des Verfahrens von van de Kassteele, Eilers und Wallinga ([Epidemiology, 2019](https://doi.org/10.1097/ede.0000000000001050){target="_blank"}). Für die berichteten Zählwerte pro Meldedatum und Verzögerung wird eine negative Binomialverteilung angenommen. Die erwarteten Werte werden mittels einer zweidimensionalen P-Spline-Oberfläche und weiteren Kovariablen modelliert. Diese Oberfläche wird für die noch nicht beobachteten Kombinationen von Datums- und Verzögerungswert extrapoliert. Der Nowcast für ein Meldedatum entspricht dann der Summe über die entsprechenden beobachteten und extrapolierten Zählwerte pro Verzögerungsdauer. Vorhersageintervalle werden per Monte-Carlo-Simulation aus der entsprechenden prädiktiven Verteilung generiert. Die vereinfachte Version des Modells enthält keine Interaktionsterme für Kalenderzeit und Verzögerung und keine Unimodalitäts- oder Boundary-Restriktionen. Das Modell wird mittels des R-Pakets [mgcv](https://cran.r-project.org/web/packages/mgcv/index.html){target="_blank"} angepasst.
</blockquote>
</details>


<details><summary>*RKI-weekly_report* (Robert Koch Institut)</summary>
<blockquote>
Hierbei handelt es sich um Schätzungen, die zunächst jeweils Donnerstags in den [Wochenberichten des Robert Koch Instituts](https://www.rki.de/DE/Content/InfAZ/N/Neuartiges_Coronavirus/Situationsberichte/Gesamt.html){target="_blank"} veröffentlicht wurden und mittlerweile täglich im [COVID-19 Trends Dashboard](https://www.rki.de/DE/Content/InfAZ/N/Neuartiges_Coronavirus/Situationsberichte/COVID-19-Trends/COVID-19-Trends.html?__blob=publicationFile#/home) erscheinen. Diese basieren auf einer modifizierten Variante der [Nowcastingberechnung zur 7-Tage-Inzidenz](https://www.rki.de/DE/Content/InfAZ/N/Neuartiges_Coronavirus/Projekte_RKI/Nowcasting.html){target="_blank"}.
</blockquote>
</details>


<details><summary>*SU-hier_bayes* (Universität Stockholm)</summary>
<blockquote>
tba
</blockquote>
</details>


<details><summary>*SZ-hosp_nowcast* (Süddeutsche Zeitung)</summary>
<blockquote>
Die SZ schätzt die Werte für das Nowcasting der Hospitalisierungsinzidenz auf Basis der Abweichungen zwischen täglich veröffentlichten und nachträglich korrigierten Werten, die durch Nachmeldungen entstehen. Dabei werden die archivierten Datensätze des Robert-Koch-Instituts (https://github.com/robert-koch-institut/COVID-19-Hospitalisierungen_in_Deutschland) der vergangenen 60 Tage analysiert. Jeweils für die 25 Tage vor dem letzten Datum im Datensatz wird berechnet, um wie viel Prozent der an späteren Tagen gemeldete korrigierte Wert von der ursprünglich gemeldeten Hospitalisierungsinzidenz abweicht. Für diese abgeleiteten Multiplikationsfaktoren werden Quantile berechnet. Die aktuell veröffentlichte Inzidenz wird mit den berechneten Quantilen multipliziert, um die Hospitalisierungsinzidenz zu schätzen. Abschließend wird die Hospitalisierungsinzidenz über ein Drei-Tage-Fenster geglättet, um unrealistische größere Schwankungen auszugleichen.
</blockquote>
</details>


<details><summary>*Epiforecasts-independent* (London School of Hygiene and Tropical Medicine / epiforecasts)</summary>
<blockquote>
Ein semiparametrisches Nowcasting-Verfahren für rechszensierte Hospitalisierungen nach Datum des positiven Tests. Hospitalisierungen werden mittels eines Random-Walk auf der log-Skala modelliert. Reporting-Verzögerungen werden anschließend parametrisch mit einer log-Normalverteilung modelliert, wobei der log-Erwartungswert und die log-Standardabweichung einem wöchentlichen Random-Walk mit gemeinsamer Standardabweichung folgen. Wochentagseffekte im Reporting werden mit zufälligen Effekten modelliert, wobei Feiertage wie Sonntage behandelt werden. Nowcasts für Altersgruppen und geographische Einheiten werden jeweils separat erstellt (daher der Name des Modells). Das Modell ist im R-Paket [epinowcast](https://epiforecasts.io/epinowcast){target="_blank"} implementiert. Der Analyse-Code ist [hier](https://github.com/epiforecasts/eval-germany-sp-nowcasting){target="_blank"} verfügbar. Anmerkung: In einer zweiten Version des Modells (bisher nicht angezeigt) werden die verschiedenen Zeitreihen gemeinsam modelliert ([Epiforecasts-hierarchical](https://github.com/KITmetricslab/hospitalization-nowcast-hub/tree/main/data-processed/Epiforecasts-hierarchical){target="_blank"}).
</blockquote>
</details>

<br>

<details><summary>*NowcastHub-MeanEnsemble* </summary>
<blockquote>
Dieses Ensemble berechnet sich als der quantilsweise Mittelwert der eingereichten Modelle mit vollständigen Nowcasts (28 bis 0 Tage vor dem aktuellen Datum).
</blockquote>
</details>

<details><summary>*NowcastHub-MedianEnsemble* </summary>
<blockquote>
Dieses Ensemble berechnet sich als der quantilsweise Median der eingereichten Modelle mit vollständigen Nowcasts (28 bis 0 Tage vor dem aktuellen Datum).
</blockquote>
</details>

<br>

<br>

### GitHub Repository und Nutzung von Ergebnissen

Alle Nowcasts sind unter offenen Lizenzen in einem [öffentlichen GitHub Repository](https://github.com/KITmetricslab/hospitalization-nowcast-hub) verfügbar. Sie können für eine Vielzahl von Zwecken weiterverwendet werden, sofern die Quelle angegeben wird (siehe die entsprechenden Lizenzfiles für Details). Wenn Sie Nowcasts aus dieser Plattform für öffentliche Darstellungen weiterverwenden freuen wir uns über eine kurze Nachricht an das Organisationsteam oder die Autoren des jeweiligen Nowcasts.
<br>
Derzeit werden Nowcasts aus unserer Plattform z.B. von [Zeit Online](https://www.zeit.de/wissen/aktuelle-corona-zahlen-karte-deutschland-landkreise), der [Neuen Zürcher Zeitung](https://www.nzz.ch/visuals/corona-deutschland-alle-zahlen-und-regeln-ld.1656184) dem [Norddeutschen Rundfunk](https://www.ndr.de/nachrichten/info/Corona-Wie-hoch-ist-die-Hospitalisierungsrate-wirklich-,hospitalisierung106.html) sowie dem [Südwestrundfunk](https://www.swr.de/swraktuell/coronavirus-karte-100.html) verwendet.

<br>

### Evaluationsstudie

Wir planen, die verschiedenen Nowcasting-Verfahren in einer prospektiven Evaluationsstudie systematisch zu vergleichen. Hierfür haben wir ein [öffentliches Studienprotokoll](https://osf.io/mru75/){target="_blank"} hinterlegt (ähnlich dem [Protokoll](https://osf.io/zkdvb/){target="_blank"} zu einer früheren [Studie über Kurzzeitvorhersagen](https://www.nature.com/articles/s41467-021-25207-0){target="_blank"}).

<br>

### Bundeslandspezifische Erhebungen der Hospitalisierungsrate

Einige Bundesländer veröffenltichen vom RKI abweichende Daten zur Hospitalisierungsinzidenz, bei denen die Verzugsproblematik teils weniger ausgeprägt ist oder zusätzliche Informationen zur Unterscheidung zwischen Einlieferungen *mit* oder *wegen* COVID-19 verfügbar sind (Details zur Erhebung sind in der Regel auf den entsprechenden Seiten verfügbar):
[Berlin](https://data.lageso.de/lageso/corona/archiv/berlin-website-2022-02-03.html#start),
[Bremen](https://www.gesundheit.bremen.de/corona/zahlen/corona-fallzahlen-37649),
[Mecklenburg-Vorpommern](https://www.lagus.mv-regierung.de/Gesundheit/InfektionsschutzPraevention/Daten-Corona-Pandemie),
[Niedersachsen](https://www.niedersachsen.de/Coronavirus/aktuelle_lage_in_niedersachsen/niedersachsen-und-corona-aktuelle-leitindikatoren-203487.html),
[Nordrhein-Westphalen](https://www.giscloud.nrw.de/corona-dashboard-desktop.html), 
[Rheinland-Pfalz](https://lua.rlp.de/de/unsere-themen/infektionsschutz/meldedaten-coronavirus/covid-19-wochenberichte/), 
[Sachsen](https://verbraucherschutz.sachsen-anhalt.de/hygiene/infektionsschutz/infektionskrankheiten/coronavirus/).

<br>

### Verwandte Projekte und Analysen

- Der [europäische](https://covid19forecasthub.eu/){target="_blank"}, [US-amerikanische](https://covid19forecasthub.org/){target="_blank"} und [deutsch/polnische](https://kitmetricslab.github.io/forecasthub/){target="_blank"} COVID-19 Forecast Hub mit Kurzzeitvorhersagen von Fall- und Todeszahlen (eine bis vier Wochen voraus).
- [Nowcasts für Fallzahlen und die effektive Reproduktionszahl in Deutschland](https://www.rki.de/DE/Content/InfAZ/N/Neuartiges_Coronavirus/Projekte_RKI/Nowcasting.html){target="_blank"} des Robert Koch Instituts.
- [Nowcasts für Fallzahlen und die effektive Reproduktionszahl in Bayern](https://corona.stat.uni-muenchen.de/nowcast/){target="_blank"} der CODAG Gruppe an der LMU München.
- Der [US Scenario Modelling Hub](https://covid19scenariomodelinghub.org/){target="_blank"} mit längerfristigen Szenario-Projektionen.
